### ISSUE TITLE
Upgrade to RabbitMQ Client 6.0.0

### ISSUE THREAD

**Issue by zgabi** [Shuttle/Shuttle.Esb.RabbitMQ#13]
RabbitMQ Client 6.0 is still a pre-release version, but sooner or later it will be released. 

It contains some breaking changes:
- timeout properties are using TimeSpan
- Subscription class was removed
- data is returned in a ReadOnlyMemory<byte> instead of byte[]

I have a fork for this upgrade, I'll send a PR once stable version will be released:
https://github.com/zgabi/Shuttle.Esb.RabbitMQ/commit/3dabce21b9e653f2db709dc0adf0764ddb03d33a

**Comment by eben-roux** [comment]
That is fantastic!  Thanks once again.

**Comment by eben-roux** [comment]
Hi Gábor,

I have released v11.0.2 with your PR included:

- https://github.com/Shuttle/Shuttle.Esb.RabbitMQ/releases/tag/v11.0.2

Thanks so much for the upgrade.

**Comment by zgabi** [comment]
Thank you very much for the merge.
